version: '3'

services:
  deploy-api:
    image: deploy-api
    pull_policy: never
    restart: always
    container_name: deploy-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/auto-deploy:/opt/auto-deploy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy-api.rule=Host(`api-deploy.thiagosol.com`)"
      - "traefik.http.routers.deploy-api.entrypoints=https"
      - "traefik.http.routers.deploy-api.tls=true"
      - "traefik.http.services.deploy-api.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    environment:
      - RUST_LOG=info
      - SSH_PRIVATE_KEY_PATH=/opt/auto-deploy/ssh/deploy_key
    networks:
      - external-sol-apis
      - logging-network
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        loki-external-labels: "service=deploy-api,type=service"
        loki-retries: "5"
        loki-batch-size: "400"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 100M

networks:
  logging-network:
    external: true
  external-sol-apis:
    external: true
